name: TestDuckdB
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Do test
        shell: bash
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v0.9.1/duckdb_cli-linux-amd64.zip
          unzip -q duckdb_cli-linux-amd64.zip
          chmod +x duckdb
          ./duckdb -c "INSTALL httpfs; INSTALL aws; FROM duckdb_extensions();" && echo "Works!"
